version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      REDIS_HOST: redis
      MONGO_HOST: mongo
    depends_on:
      - redis
      - mongo

  redis:
    image: "redis:4.0"
  mongo:
    image: "mongo:3.6"
